# nixpacks.toml

[phases.build]
# Instala dependencias y construye ambos proyectos
cmds = ["pnpm install --frozen-lockfile", "pnpm run build"]

# Configuraci贸n para el servicio de API (backend)
[start.api]
# Comando para iniciar la API en producci贸n
cmd = "pnpm run start:api"

# Configuraci贸n para el servicio Web (frontend)
[start.web]
# Comando para iniciar el frontend en producci贸n
cmd = "pnpm run start:web"

# Variables de entorno que Nixpacks debe conocer
[variables]
NODE_ENV = "production"